language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5']
      env: COMPILER=g++-5
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-8']
      env: COMPILER=g++-8
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang

dist: trusty
sudo: false

script: cd tests && make && make test
