language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5']
      env: COMPILER=g++-5
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-8']
      env: COMPILER=g++-8
    - os: linux
      compiler: clang
        apt:
          sources: ['llvm-toolchain-trusty-6.0']
          packages: ['clang-6.0']
      env: COMPILER=clang++-6.0
    - os: linux
      compiler: clang
        apt:
          sources: ['llvm-toolchain-trusty-7']
          packages: ['clang-7.0']
      env: COMPILER=clang++-7.0
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang

dist: trusty
sudo: false

script: cd tests && make && make test
